##
## BPF Masquerade should be enabled for use with Talos and host DNS (`machine.features.hostDNS.forwardKubeDNSToHost`)
## CNI exclusivity should be false and endpoint routes enabled for use with Istio
##
########

---
autoDirectNodeRoutes: true
bpf:
  masquerade: false # Required for Talos `.machine.features.hostDNS.forwardKubeDNSToHost`
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 1
  name: arc1
cni:
  exclusive: false
endpointRoutes:
  enabled: true
envoy:
  enabled: false
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.246.0.0/16
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
bgp:
  announce:
    loadbalancerIP: true
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: snat
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
