---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app boltz
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      boltz:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/boltz
              tag: latest@sha256:9f3ecd0a56a8d52dc50e63759f0a7dc75c8c8bf51f8a83d5e9f263ce91046b40
            command: ["tail", "-f", "/dev/null"]
            env:
              TZ: ${TIMEZONE}
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
            securityContext:
              capabilities.drop: ["ALL"]
            resources:
              requests:
                cpu: 200m
                memory: 8Gi
              limits:
                cpu: 16
                memory: 48Gi
                nvidia.com/gpu: 4
    service:
      app:
        controller: *app
        annotations:
        ports:
          http:
            port: &port 80
    persistence:
      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
