# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:N9GK8Z9jebDnhacr+sZaR8qAm31YKPIXg0tNxyudnCo=,iv:mXmIl1UeJGxtj5/a9nuGwUPn1kAVdi3YF9+QPWjDX8Y=,tag:MQqSVHV7hwPe0yoAmg9LXw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOFVaVXZLemhxZUxyNWFC
        NEZpa05rcExuRjRSQ3ozY3ZzOTFRbFhDQ3lVClgxRjl6SEVKb1RDb2FwMFo2aUFS
        YnpwNDhrQXNjaXhjMlUrUzZVeHlySlUKLS0tIFdBUjFPUjVXcVNzbGlidzdxZDhT
        dUpYR2tUeG0rbjZ6aGh5WTR1U2h1QnMKCoC6D9+QWQLrWRMZhuBOluNuHQwgqaU/
        UBs2nuNdX/aeEgWemx+sWXlxbg9enF4K1mfkq6Cp6wfKtILfZ2QL/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-14T01:18:57Z"
  mac: ENC[AES256_GCM,data:KI48AIaiGscZRPLSOEDNehh4Ob2+MozntxybUfEcpPF4Qv0S26n60Yuh6nMQV8ySSCEHloL0enKNLKilIpIoORBP9CUZTDVbDhMTkCFixT7XkovwrS++oYdfKAdEoPNtVntb8jBaQlVUhsGT7D5SYRKyTNAAaFBxu+o5nY2nA0s=,iv:9D5NRso16Viihsbsph2HWsC06DRik2+FAUyUEi5wsYE=,tag:UEwR/+865ms/nxcu35OmpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
