---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./promtail/ks.yaml
  - ./loki/ks.yaml
  - ./netshoot/ks.yaml
  - ./healthchecks/ks.yaml
