---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qlora
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      qlora:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/qlora
              tag: rolling@sha256:e2f24bb15b8b363cc0ff98c674837f495ab37938da778fca8f16ee5e4916e90e
            command: ["tail", "-f", "/dev/null"]
            env:
              # GITHUB_REPO: https://github.com/RareCompute/example-models
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
            securityContext:
              capabilities.drop: ["ALL"]
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: "16"
                memory: 24Gi
                nvidia.com/gpu: 4
            #            probes:
            #              liveness:
            #                enabled: true
            #              readiness:
            #                enabled: true
            #              startup:
            #                enabled: false
            #                spec:
            #                  failureThreshold: 30
            #                  periodSeconds: 5
    service:
      app:
        controller: *app
        annotations:
        ports:
          http:
            port: &port 80
    persistence:
      workspace:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 2048Gi
        retain: true
        globalMounts:
          - path: /workspace
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
