---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubelet-csr-approver
  namespace: flux-system
spec:
  targetNamespace: system-controllers
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/arc1/apps/system-controllers/kubelet-csr-approver/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
