---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ligandmpnn
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ligandmpnn:
        type: deployment

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"

        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/ligandmpnn
              tag: rolling@sha256:dc659f4bfbc8b85a7ef8728633913099056217634888452f98596eb9c2304ef4
            command: ["tail", "-f", "/dev/null"]
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              SEED: 111
              PDB_PATH: "/app/inputs/1BC8.pdb"
              OUT_FOLDER: "/app/outputs/default"
              MODEL_TYPE: "ligand_mpnn"
              CHECKPOINT_LIGAND_MPNN: "/model/ligandmpnn_v_32_005_25.pt"
            securityContext:
              capabilities.drop: ["ALL"]
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: "16"
                memory: 8Gi
                nvidia.com/gpu: 4

    service:
      app:
        controller: *app
        annotations:
        ports:
          http:
            port: &port 80

    persistence:
      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace

      tmp:
        type: emptyDir
