# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: openssh-server-secret
stringData:
  PUBLIC_KEY: ENC[AES256_GCM,data:0wZ9oLYxlsftUvDzX9ESaU2v7OoCrpR8FiPvdEQ046X/7n16dAq5sKKpX0x6VzzZAGD3rC+GrPI46UR9XdPd033HDZOd8ZhiTwqLDG4b5jux4J5ppS4LP0VI4eDzITP3dCnECnYW0ktzUiDns2myW6LKpUFps2M1ezor7aY2MNfLCTRz9kh0/PiV5WIsgaKNnMrDBwf/djUQxslK1RnpgpT/X4u/rNiSbTED5AsSyHiEPBHSacRlhQX9uqt+KX9oRbfsxbMh0HRr1p3Z1jVeUmGnfXWpRzC41DeAYchUN7a9gmLPl5S9Jimy1dCMtAtrxC2THgb1LuSCNifoWv4RSHwNFFrmrJ0ZC6+vuDLqHG/MrGNsun1elWh8Is6o5cBw+CZW10BkAdBc8ZmEaS3EMW5ohd8PhUXq1ec9UfuL2l8NLouWElgCDOcBQBgX+ZIsDhkqkVDogiDi++IQ1cvFDpqvOdI407GrtCNeN6y0IBoLGuUHMU81U0MiPsEvgoQdXXi92RZXa+8eDpR5+mxOR6C0KobcpDeKDVdsAQhPKgEA1aq8FRdApQUhli7e3KK5AA9gJ+C4xZLBRljhhEtGgMrEClTHb1OpDMOAPOnytyT7wlrMtkL0+FcACnwzYvWt+GJjj1PBQOO4dN1ZxFBl/bDYkaeih8+zn6PBUw2o2F1fYZ14lfQId4YGjkL6ygaPLUlQWYOpBW9i6EQwgJ7fsyJQLtPc+cGj3y22BjyPDsfSd8r+uUrTtxZRVAGsW375c3L5FkYWViHvV5mGV9cDTymDM6j0RNGqFcUIAZPwTJoTSNzm8qyzRkrHLneG1W8MgTo2Ed/N2aFdw0JvedONSQmsohM4yMdp4BKBj1NcSl+Tj6rWu00u5Kf6LGsGhbq5266HqSuCfs1fJDUzTs6Ycn19PoCNQyCEbIXwiyIIZAlyWXJlnnxKLPekPX8GxafR+914EeMv8L3f1WaKwS1q,iv:LZ/V0O8ee8m223dCnET12IYjh/PCDQGxTAh/wKXKqDI=,tag:B8vSuo57dfOa9/SqWqf6gg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc3VSaThmRWRtZkJ2dzNE
        L05BUUJMKzAvMzhWbzBVMWJXTmFlKzBLeWtrCmRGd2dTUEgzRE1pMlpXZnRidnpN
        QWV1bEQ5L1A0bURLUzNCSVlzWXNBK1EKLS0tIFpzM1F1V3JKdlZDUG91dVh2Q1dH
        NnVHUVBFR09TUVMzTTdXd0hyL01VbmcKLMUE2WCfeZe0nGAnLE5aEObJ7jQZrgxs
        /RxcHro/+PKA7JT/vf9JQimJ/9s/iyU5pS89FLxePSolIK3GHb6Ajw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-08T03:01:01Z"
  mac: ENC[AES256_GCM,data:Xo+UF9+1Ybe2X+fR9c+JWmQmEIlDQ+svWtNsFEo0PbrBfjShrGFxnHPLYrL7vo6U0lVuPDMcOxfZYlxA6lxuMbVYqgKpJYndiYzyQRE1ieB/dgTNNKtGUXEF5w2aspVqnryese0D6+sPLXXjmhIH9NTH6ab6A0HGzSD/SLwMhbw=,iv:A3VmD7bca1For/+ca32StaFEGXMXXKAgeQvmzN9q0NM=,tag:4HGEZ793Q+z8RIk9T971OQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
