---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/onedr0p/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
        exclude: rbac.yaml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
