---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  interval: 30m
  chart:
    spec:
      chart: k8tz
      version: 0.17.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    namespace: network-system
    replicaCount: 3
    timezone: "${TIMEZONE}"
    cronJobTimeZone: true
    webhook:
      certManager:
        enabled: true
        issuerRef:
          name: k8tz-webhook-selfsign
          kind: Issuer
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8tz
              topologyKey: kubernetes.io/hostname
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Namespace
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Namespace
              metadata:
                name: not-used
