---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dev-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      dev-server:
        replicas: 1
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &secret dev-server-secret
        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/devserver
              tag: rolling@sha256:239d9e8763ffbc8abfc20bee148133288e0ffc953014b0590256e9c6c582dff0
            env:
              USER_NAME: amelie
              SUDO_ACCESS: false
              UID: 1000
              GID: 2000
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 4Gi
        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
    service:
      app:
        type: LoadBalancer
        controller: dev-server
        ports:
          ssh:
            port: 22
            targetPort: 2222
        annotations:
          io.cilium/lb-ipam-ips: "${LB_DEVSSH}"
    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 100Gi
        retain: true
        globalMounts:
          - path: /config
      config:
        type: configMap
        name: dev-server-config
        globalMounts:
          - subPath: init.sh
            path: /custom-cont-init.d/init.sh
            readOnly: true
          - subPath: help.sh
            path: /etc/profile.d/help.sh
            readOnly: true
          - subPath: packages.sh
            path: /etc/profile.d/packages.sh
            readOnly: true
          - subPath: motd
            path: /etc/motd
            readOnly: true
      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace
      tmp:
        type: emptyDir
