---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dev-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    serviceAccount:
      name: ml-kubectl-access

    controllers:
      dev-server:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &secret dev-server-secret

        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/devserver
              tag: rolling@sha256:4ab3a9dc48c5c0e327161bf109551c058fa708591052a9d4434c7263a409f1d7
            env:
              USER_NAME: amelie
              SUDO_ACCESS: true
              UID: 1000
              GID: 2000
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 250m
                memory: 8192Mi
              limits:
                cpu: "64"
                memory: 128Gi

        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
    service:
      app:
        type: LoadBalancer
        controller: dev-server
        ports:
          ssh:
            port: 22
            targetPort: 2222
        annotations:
          io.cilium/lb-ipam-ips: "${LB_DEVSSH}"

    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 65Gi
        retain: true
        globalMounts:
          - path: /config

      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace

      config:
        type: configMap
        name: dev-server-config
        globalMounts:
          - subPath: init.sh
            path: /custom-cont-init.d/init.sh
            readOnly: true
          - subPath: custom.sh
            path: /etc/profile.d/1-custom.sh
            readOnly: true
          - subPath: packages.sh
            path: /etc/profile.d/2-packages.sh
            readOnly: true
          - subPath: help.sh
            path: /etc/profile.d/3-help.sh
            readOnly: true
          - subPath: rare.sh
            path: /etc/profile.d/4-rare.sh
            readOnly: true
          - subPath: kubeconfig.sh
            path: /etc/profile.d/5-kubeconfig.sh
            readOnly: true
          - subPath: motd
            path: /etc/motd
            readOnly: true

      tmp:
        type: emptyDir
