---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rbac.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: dev-server-config
    files:
      - init.sh=./resources/init.sh
      - help.sh=./resources/help.sh
      - rare.sh=./resources/rare.sh
      - custom.sh=./resources/custom.sh
      - kubeconfig.sh=./resources/kubeconfig.sh
      - packages.sh=./resources/packages.sh
      - motd=./resources/motd.txt
generatorOptions:
  disableNameSuffixHash: true
