# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
type: Opaque
stringData:
  ADMIN_PASSWORD: ENC[AES256_GCM,data:xa904kSXt07mzuTkPH1njD0NuILrWU58//v98egDGV+6Awm5IiM7H5k2,iv:xLPsixgJVzqUMt3w6ylQ7ydFWPISMmvSvjsnt5E0eP4=,tag:K4ehrKfrYrUtY6pmgGHrTg==,type:str]
  AIRFLOW__WEBSERVER__SECRET_KEY: ENC[AES256_GCM,data:2Soj4BgQ8T9YbdvwA4f/yrGXjfpWZGYyDyeZyk+NYFTkrx/neGtohMt7CEn6bx97hh3zQ5Gch+7uyCVjg0FbiA==,iv:xwrhSNoQtsModVKJtziBrsG0mJDstmtA2Uwxs7A0lD4=,tag:p448CO7XPE+RJs7LMXGSDg==,type:str]
  AIRFLOW__CORE__FERNET_KEY: ENC[AES256_GCM,data:zg/YOO4faex9PXKGFpMEWIp7wgMw1XIwjHU8Sv2sWb2zUAHVojEVv8s0ZneNYtddkGoCytzPx3m/LsauTiFobQ==,iv:vuhIjqiznHoYKCofAmDnmnsJR27nToKoAxKACXf8gvY=,tag:WWcIMvmYibPDU9nnxhn5vQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:tPjwnI5KNZXtdv9FZI8MYA==,iv:JoJGwfLthGuturyRQbxyYNUrIAeYOCAi0nFcNRF7Tr0=,tag:wR+APyT0KbgKqrB/lwrCdg==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:m8Vp64DBRnatxls9DUNClB7RFFMG7snAbQJERnkIaL7X,iv:ppf222OtpPV3KfxxTiaXWZl9f5a1ErXY5PS2KcG1k4I=,tag:6DiDRVkYouLyJLhjG/mIfw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja2F4ODdoZUg3SmJHWlFp
        b2p5T01pRHZzNmtaSnFJRUZSQW5TOTRNQWxjCkl3cEJ5S3N4WC9nT0dLV1ZDVnZK
        Uy9iUDhnMndsT05iNzN5T1RuQnlsSWsKLS0tIHhYMlRzQmxsVCs4Q2RqQVlBSXJX
        MVhHTVZiSHhlU0paZXpLSkFxczhIWmsKB/n26k6P30UB+RDl12TIAJaaJmGSqtaf
        Zt2mEl917EkJNU12WU6uHBu5NuAM7hkJjJhAsUeHGTQMiCEf0i3JMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-24T18:51:46Z"
  mac: ENC[AES256_GCM,data:r+tP9wbH5todaazYEjJZ+JHDytMtxJVoidyWJuFXSLEt+l7ZnYKuvEsEm9P7mP53m12tYuhQb+n99ZP/EyiK6N39Ncxwrfjl2jMae5RspQYY/MxyPgE8mMtQuO+aBChtZ7tegL7l/Zv0JYVYJd9FT+cdw+7K+mTL0ck/heToen8=,iv:WxkZbCg4WLAaUoCALFeF+cE/dZT4M2eGQhDA3AaEHBQ=,tag:5R97e+QQDDTdJHXw1HsFmQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
