---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./homepage/ks.yaml
  - ./archivebox/ks.yaml
  - ./miniflux/ks.yaml
  - ./changedetection/ks.yaml
  - ./atuin/ks.yaml
  - ./it-tools/ks.yaml
  - ./cyberchef/ks.yaml
