---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lldap:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: lldap-secret
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: 2024-11-09-alpine-rootless@sha256:bdebc2219927eb7557c87c3e55f9a597b9d6d6d5be74b330cd0a8c124f3069ee
            env:
              TZ: ${TIMEZONE}
              LLDAP_HTTP_PORT: &httpPort 8080
              LLDAP_LDAP_PORT: &ldapPort 1389
              LLDAP_LDAP_BASE_DN: dc=rare,dc=arpa
              LLDAP_HTTP_URL: https://{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}
              LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: false
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/name: LLDAP
          gethomepage.dev/description: LDAP server
          gethomepage.dev/icon: mdi-account-key
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: lldap-tls
            hosts: [*host]
    persistence:
      data:
        type: emptyDir
    service:
      app:
        controller: *app
        ports:
          http:
            port: *httpPort
          ldap:
            port: *ldapPort
