# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lldap-secret
  namespace: security
stringData:
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:xFPIUXamCfwDVBASUPWaNnzPGoIrgEsZQNL2+955qzH+TrntkUiX5u+A1/20RELKyc1vH+W2hIg5AjMsR74/Zw==,iv:4K2TCXjunF7bQxT2iIVd17H1wqW7TdkWDr3RSUCm8hA=,tag:CcMmYtkF0vTeLoY8wNdC1g==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:xY6IcloM6jjPQi9CkUcWe+/0C4z5CJPCQpdpOCAzGHy5nCw8pzX8VBlbzw1tM0HiEtUMDHGVc276P3Ry6rwaVg==,iv:dgpPeMY/MYkKQuakx2R6oFAIMiUxrRlUvDFiy170ka8=,tag:zZwoP7hG45i/g6MTE3drjQ==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:CQf/q2qfpjoa0LsdbCiO,iv:WBuHn4fthqdsNhnsM1VavG0x+qIwySs3y4NIvU5ysFo=,tag:AM48Evj9WxHyAYiUXrNobA==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:+RabLRCUC7GydnNVgyYLFiRd77Q=,iv:V1Ut/5IhLd95uFlH2BbP96a/0pCpccpM/ul+2FCD9ow=,tag:FP570rQoVy3Smkjt/ORNlw==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:8/UKosFEOvYwebPQ2sCKv2LBkz7VKwiRf5ocxb59uZE=,iv:fBrCnBVl7ghBiADgMr+7TZTFxGzZgWv0yw0UXyduWHA=,tag:5Ub1MlLyTyRlF3CoU3vCFg==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:e0Glt29Icl1/UuRQ3OYUhAaTouT/2O6U1rsrcfdOccqsr/1so/nY1F7AoPqHEBeYtYJ6Fjffao3MwQpWUalFNLkNq0eCkIffxHTTUuknz7yl7zDVpG/8E/OjGNDhIc5fbJwv7I1F02b4ntZuvDPa4A==,iv:fpPNbMEsmPoizRzlVLQ6nYeGCmHwC79G8ANNxhzuWcM=,tag:dc7dgX0naVJOKU3uEIQ2sw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ef3isUY=,iv:eLswUyAEmMBUawQlvWEBf+PQBZQlcp6dsncOZVO/UEw=,tag:P0Vwb+5EubusenVh0MhtDQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:u6mBmc7YoJGpGspHoiDOSexQhtUmNBDOslQtljC1/kd3GDhNni8cYA==,iv:hUldJ3ZSAda0gL4/UoLtpfl9v55e9tNZX608heOBojU=,tag:D2PxPt9J0s09mqeZqM8YuQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:xnKSduw=,iv:/KUJsJD1OIjdmF4LmCF9/au85n6/YEdts6cF4lbkP9Y=,tag:iGS89OJHLEkcffmbUUb40Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Nz6sWhZncsWqOwpxnDRdbr+OllkWpJatbZE9ep+44K9et88PyGmhD/IcQGazMnGl,iv:vtoEbcvQZHEoMvBPZDTv6lERgOl/lJjVwSNpAOtBRzo=,tag:Z3NXMbq4rmR7pxxG6r/DPw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:4F+ElyM1n8xEhtuqut0442TuUUG1rD7XjWi68EBi+m2NL4W9d1wCmnkai3+afUVx,iv:2hq/oSZVcX0t8vZgAom1P2thxSHHL8r0QRxv6p9aLF4=,tag:u05qm2qslHYPDe/OOI3PjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY0dBSitmRDhPc1ZiWGJQ
        bXpUSUY5RnUxMmNDbUc0UDYvNTJJb3NuYjB3ClNFNGdxRHNOcWRNMS9kL1BpN2Vp
        SEVUSzlDUkZTeTBSSjE4c0Jtbjg3WkEKLS0tIG5YVHRlVnQ0eE5jTzlIYTdZYXgv
        YXE5ZkF2RUNra2sxN2xTMVI2WTBxcVUK25ycLDIRXIVt5wo2GXizKJciW2DhjPTh
        59fFMXLSbxLUG9IF306pq020G3zXhv+/lPwmGUO7Wjomgy4E0eLtEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-22T20:54:03Z"
  mac: ENC[AES256_GCM,data:iJ8eWnFm8RdblyUv40m2218Z9RitbwuCVYVsGRLqq/eenAdhvQjuTpdCojFhHi9kmSalfVZo9ANdy80CtQ0s5qM+gyAoJtjpWCqgP3oY3KstP2dt9e8yfTTFx0QbOzXyEScud4ewviyc/14XUPLOi0T+X4eT4LbjLsDcvXmI+qI=,iv:0rz5pdbJv8mH0ggB67Y37Bf28mmlfXzVbenT/RVq1h0=,tag:1OP/r/VUiBUj/gBGvRUM5w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
