---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rfdiffusion
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      rfdiffusion:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
        containers:
          app:
            image:
              # https://github.com/RareCompute/containers/pkgs/container/rfdiffusion
              repository: ghcr.io/rarecompute/rfdiffusion
              tag: rolling@sha256:9c6359a3a1e3c65728605baca79692d4ef1ab92df018cb8dd9e8b87534c50ba7
            command: ["tail", "-f", "/dev/null"]
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              USE_MSA_SERVER: True
              rfdiffusion_DOWNLOADS_DIR: "/workspace/rfdiffusion/cache"
            securityContext:
              capabilities.drop: ["ALL"]
            resources:
              requests:
                cpu: 200m
                memory: 4Gi
              limits:
                cpu: 100
                memory: 24Gi
                nvidia.com/gpu: 4
    service:
      app:
        controller: *app
        annotations:
        ports:
          http:
            port: &port 80
    persistence:
      sharedmem:
        type: emptyDir
        medium: Memory
        sizeLimit: 64Gi
        globalMounts:
          - path: /dev/shm
      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace
      models:
        type: emptyDir
        globalMounts:
          - path: /models
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
