---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rfdiffusion
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      rfdiffusion:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/rfdiffusion

              # renovate: datasource=docker depName=ghcr.io/rarecompute/rfdiffusion
              tag: rolling@sha256:ea4a27b0e1c87814d9bca3b00b0bc65905981f2d8b01efd8967381add63a54f4
            command: ["tail", "-f", "/dev/null"]
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              DOWNLOAD_ALL: true
            securityContext:
              capabilities.drop: ["ALL"]
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: 16
                memory: 32Gi
                nvidia.com/gpu: 4
    service:
      app:
        controller: *app
        annotations:
        ports:
          http:
            port: &port 80
    persistence:
      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace
      models:
        type: emptyDir
        globalMounts:
          - path: /models
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
