---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app reloader
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/arc1/apps/system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
