---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app jupyterhub
spec:
  interval: 30m
  chart:
    spec:
      chart: jupyterhub
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: jupyter
        namespace: flux-system
  values:
    hub:
      existingSecret: jupyter-secret
      db:
        type: postgres
    singleuser:
      storage:
        type: dynamic
        capacity: 8Gi
        dynamic:
          storageClass: local-nvme
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Research
        gethomepage.dev/icon: jupyter
        gethomepage.dev/name: JupyterHub
        gethomepage.dev/description: JupyterLab orchestration tool
      hosts:
        - &host "jupyterhub.${SECRET_INTERNAL_DOMAIN}"
      tls:
        - secretName: jupyterhub-tls
          hosts: [*host]
