---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-tls
  namespace: security
spec:
  secretName: teleport-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "teleport.${SECRET_EXTERNAL_DOMAIN}"
    - "*.teleport.${SECRET_EXTERNAL_DOMAIN}"
