---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teleport
spec:
  interval: 30m
  chart:
    spec:
      chart: teleport-cluster
      version: 16.4.6
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    clusterName: teleport.${SECRET_EXTERNAL_DOMAIN}
    chartMode: standalone
    kubeClusterName: ARC1
    validateConfigOnDeploy: true
    enterprise: false
    auth:
      annotations:
        deployment:
          reloader.stakater.com/auto: "true"
      teleportConfig:
        auth_service:
          client_idle_timeout: 2h
          client_idle_timeout_message: "Connection closed after 2hours without activity"
          session_recording: "off"
    proxy:
      annotations:
        deployment:
          reloader.stakater.com/auto: "true"
      teleportConfig:
        proxy_service:
          trust_x_forwarded_for: true
    podSecurityPolicy:
      enabled: true
    log:
      level: INFO
      output: stderr
      format: text
      extraFields: ["timestamp", "level", "component", "caller"]
    ingress:
      enabled: true
      suppressAutomaticWildcards: false
      spec:
        ingressClassName: traefik
    annotations:
      ingress:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Services
        gethomepage.dev/name: *app
        gethomepage.dev/icon: teleport.png
    tls:
      existingSecretName: "teleport-cluster-tls"
    authentication:
      type: local
    proxyListenerMode: multiplex
    persistence:
      enabled: true
      storageClassName: local-nvme
    serviceAccount:
      create: true
    rbac:
      create: true
    service:
      type: ClusterIP
