---
title: Dashboard
theme: dark
color: violet
headerStyle: clean
providers:
  openweathermap: "{{OPENWEATHERMAP_API_KEY}}"
layout:
  Network:
    tab: Main
    style: row
    columns: 4
  Services:
    tab: Main
  Tools:
    tab: Main
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
