---
#- search:
#    provider: custom
#    url: https://kagi.com/search?q=
#    target: _self
#    focus: false
#    suggestionUrl: https://kagi.com/api/autosuggest?q=
#    showSearchSuggestions: true
- greeting:
    text_size: 2xl
    text: Rare Dashboard
- datetime:
    locale: en
    text_size: l
    format:
      datestyle: long
      hour12: true
      timeStyle: long
- openmeteo:
    label: Chicago
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    timezone: "${TIMEZONE}"
    units: imperial
    cache: 5
    format:
      maximumFractionDigits: 1
- kubernetes:
    cluster:
      show: true
      showLabel: false
      cpu: true
      memory: true
    nodes:
      show: false
      showLabel: false
      cpu: true
      memory: true
