---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-11-07T00-52-20Z
            env:
              TZ: "${TIMEZONE:=Etc/UTC}"
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring:9090
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_INTERNAL_DOMAIN}
              MINIO_SERVER_URL: https://s3.${SECRET_INTERNAL_DOMAIN}
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_INTERNAL_DOMAIN},https://s3.${SECRET_INTERNAL_DOMAIN}
            envFrom:
              - secretRef:
                  name: *app
            args: ["server", "/data", "--console-address", ":9001"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: &api-port 9000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 103
            runAsGroup: 103
            fsGroup: 103
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: minio
        ports:
          http:
            primary: true
            port: 9001
          api:
            port: *api-port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: api
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/name: MinIO Console
          gethomepage.dev/description: MinIO admin dashboard
          gethomepage.dev/icon: minio
        hosts:
          - host: &appHost "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: minio-app-tls
            hosts: [*appHost]
      s3:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &apiHost "s3.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: api
        tls:
          - secretName: minio-api-tls
            hosts: [*apiHost]
    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 24Gi
        retain: true
        globalMounts:
          - path: /data
