---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcgm-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: dcgm-exporter
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: dcgm-exporter
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: nvcr.io/nvidia/k8s/dcgm-exporter
      tag: 3.1.7-3.1.4-ubuntu20.04
    extraEnv:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    nodeSelector:
      nvidia.com/gpu.present: "true"
    runtimeClassName: nvidia
    resources:
      limits:
        nvidia.com/gpu: 4
    serviceMonitor:
      interval: 15s
      honorLabels: true
