---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gpu.rules
  namespace: kube-system
spec:
  groups:
    - name: dcgm-exporter
      rules:
        - alert: HighGpuUsage
          expr: |
            rate(DCGM_FI_DEV_GPU_UTIL[15m]) > 0.85
          for: 60m
          labels:
            severity: warning
          annotations:
            summary: "High GPU usage on node {{ $labels.Hostname }} for 60 minutes"
            description: "GPU usage on node {{ $labels.Hostname }} for gpu: {{ $labels.modelName }} has passed 85% for over 60 minutes"
