---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chaos-mesh
spec:
  interval: 30m
  chart:
    spec:
      chart: chaos-mesh
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    chaosDaemon:
      runtime: containerd
      socketPath: "/run/containerd/containerd.sock"
    dashboard:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Tools
          gethomepage.dev/name: *app
          gethomepage.dev/description: Chaos engineering dashboard
          gethomepage.dev/icon: mdi-fire-alert
        hosts:
          - name: "chaos-mesh.${SECRET_INTERNAL_DOMAIN}"
            tls: true
            tlsSecret: chaos-mesh-tls
