---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app loki
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 6.19.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs
  valuesFrom:
    - targetPath: loki.storage.bucketNames.chunks
      kind: Secret
      name: &secret loki-secret
      valuesKey: BUCKET_NAME
    - targetPath: loki.storage.s3.endpoint
      kind: Secret
      name: *secret
      valuesKey: BUCKET_HOST
    - targetPath: loki.storage.s3.accessKeyId
      kind: Secret
      name: *secret
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: loki.storage.s3.secretAccessKey
      kind: Secret
      name: *secret
      valuesKey: AWS_SECRET_ACCESS_KEY
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      podAnnotations:
        configmap.reloader.stakater.com/reload: *secret
        secret.reloader.stakater.com/reload: *secret
      analytics:
        reporting_enabled: false
      server:
        log_level: info
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 14d
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: local-nvme
        size: 32Gi
    backend:
      replicas: 0
    gateway:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    monitoring:
      dashboards:
        annotations:
          grafana_folder: Loki
      rules:
        enabled: false
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
        folder: /rules/fake
    test:
      enabled: false
