---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openssh-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    serviceAccount:
      name: ml-kubectl-access
    controllers:
      openssh-server:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &secret openssh-server-secret

        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/openssh-server
              tag: latest@sha256:ecc58e9c86bfeefe1b0e98d5d55cade951a45085a0b4b29a6773357b129946de
            env:
              USER_NAME: amelie
              SUDO_ACCESS: false
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 4Gi

    service:
      app:
        type: LoadBalancer
        controller: openssh-server
        ports:
          ssh:
            port: 22
            targetPort: 2222
        annotations:
          io.cilium/lb-ipam-ips: "${LB_OPENSSH}"
    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /config

      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace

      config:
        type: configMap
        name: openssh-server-config
        globalMounts:
          - subPath: init.sh
            path: /custom-cont-init.d/init.sh
            readOnly: true
          - subPath: custom.sh
            path: /etc/profile.d/1-custom.sh
            readOnly: true
          - subPath: rare.sh
            path: /etc/profile.d/2-rare.sh
            readOnly: true
          - subPath: kubeconfig.sh
            path: /etc/profile.d/3-kubeconfig.sh
            readOnly: true
          - subPath: motd
            path: /etc/motd
            readOnly: true

      tmp:
        type: emptyDir
