# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: openssh-server-secret
stringData:
  PUBLIC_KEY: ENC[AES256_GCM,data:5CyWGZGn+qBmLD4+KOPQciJ4epQ3rpoj7yQaq3kiQkA1cBhxvtJueAmrD2QhDq2Pz3SPReAPRktIctWhnew/rnJOG13pSLaUoMjTQXKfSiB08AdrLrTbXkNTNN6Ziz5ivbDqNQIl46sgX3arzuRW7TltOw3Z7blQ4+thP77mk06yXPVqy1ITl6/A2WsjsSh0oLiW3bHOfv0RDGsTkGF6hW2Azo2Jhso7BlebrPaulMiSySAdOcpdtPGc1K1AHvAJvXa5sXwTi9GoyivXiSaz7LPio4zGJ6JEQOUgu17XD05/+ParcM9L7GYLPCNLEXFAwDeyzFk6qpdZahxG/cCj/oojgpo8zO0yhLunZahKHKlJepitSaOyRFgDzv286LaOxiOnXKf1hyLi28vmomvuFKqQmouJ+bJ4sFq+pbRNmUKL+vjfrAH0OCuoT7sW6NJaG6ZBLLtCg6uGSJZWW2faUy1CwyfOUsftA+hu4eXNxWvYBkwVvL5YYZ79/3iGOvkEk6HSoOZ1kpzThEWrUSvFNrU67VJt2LELWCOBmwh1Q93nfL2p31tirX3xXarnheHWzltOi7x2DmbR/N9vE92dxzXg4+6o8snMeBYC2/E10u7Qoie9DWgRbEcMwCYLVbRVbUmnB/CVacL7YjJ7b0oMEfnQw92cUvTdpLnKXf8qUQYUkGcJoG35Vi0sgR0A/ScVjm0zthTsOVC9k7U+2DDJR1C0qQWLloXc5X4rzFsPEjYNFsFYlRpeJ6A/tKxLSETLINQ/2MPqETmh5DQ+Fe3UYq8U6iZ/dcXr2OSymL9s75D+P9JChfdTAULRRWt4mxkOHx1fHEa2JmEiWwOL4/tMm4O0YVxhCOwr3zkGn2iiHm4qMmSfvrS39mxIRDrJS0v1gG31Nw88xf6lB3dpirKp/j97nMtKkJzQjK7dKKdQNAUg8Zf/2Jv0dwQYjwenylX6ZvcLX3WcFafYTwHEX0ErLymIBqpI6UEdIdEm4URUwBEcsfS0CyCxgW2c+Fk4YrLvLG0g+ptyXXTzBNhVXZDQVg0IxNmg0Nt0lBhk2q7CY5bUdfXus5GR1kZLoAJrposB2m4jztMjzwVrf/gyDDw2EdTt/kuIeq93gx+WZUmZZdYKh6QUktX7InIizk0EGmIfJ66pZX8PrJutsp57wHBHzZksg3nZc22EdddjoGUbCLeWRQzq3BpVLDSC0CXOFfA0cuTzKSD8pMPpH/Kn8kGG9BPhC0OMDXEP3UeqoLAQs+BIYc6/d94mgZM1sabTGAT1oeIKBLO3nhG38tsCUMQKUo+SNdZDPe+UtDaSmQ/FXLsY9vhwAJDBhnt46RlhfD/Vb52ppVJ4yLdLaO1ATpC7BHuXq7uYclaQlwT2zwH3f0GoPqfL+BWvWKu/PJk0wYuixiYIMqusuwRVut+XhVa/xXv9XgxgNPBUuTe0OAgJKaZFGt+0XRdLRXVZptP33ZlHN3GYS40Os0ZiWHvyoQX4WjdiMEcOsUouKC1M/0Q23E3Y5bIMPyBff5gfEaag/7P7au0jzUn0rJjevM1BBtIqdqZyZwnXgsHfhJ57e5t0bvhn4Pm4gNESmbZz0N7P5IqFADrkL/wkFZCuUEFAMFPUj3TqKe3QoXrX1zgGi0nkvAaJfboREneOiJxR5md4Uoe8w0AoxthXz1yFBXt9a03vYy4OlM+vghwBjgsw9NOZxOhENiHTzq+7iLC9HM2AMkSYKRklIv60w9nUQz0RnA+i0CB4Y3d8yy7p0d+gCCwi1St+NibKqd+yytwIdl3OJyBXdDOcE+wBbdMkCp5vNfoWVi6ayDLphfyZidx7lnjjCU/GPlGGTVtkUtyJWWCjEeR8B76kffUBwXrftfK54duATA39Tu/ZZNiDXffZPrweUDOuf8ZIpFEikVxVcQ4MoI2cadY1ZlWfbxPgncNvqWnb9h8j+wYuG1FnBcbepgNbqEEHJg8nH8zwA1TyiXOAzuw=,iv:xUbqEtoYYU0dYR2h6ffbM2+2DB9id3tYnHoiRJ3c2PI=,tag:Dp+Lcz4YV2Hq4+YBQx1Yxg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU0JKWmgxQXJOb3hVMmtU
        OStWVVg4U0ovNzF4b3hGREQycHV1N0Y2dFVzCi9GSHFRS3ozOE5oNHZEQTVId1Fu
        VERQalloZTNQUHoycW42SGhETlpQR1UKLS0tIFZWM0syRSthci9LQS9GVzd1dEdN
        SlpTR0phblJVeEYvb2RXREpuSWh4VzQKWjC/LVScEELaOuhAMyyhGIeKiP6HOG9s
        Evo7poNDXIVx46p3EcS8RrVT5EeHEb1Qzj/2TSE6l4KOYxvUHo/Tqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-08T20:57:17Z"
  mac: ENC[AES256_GCM,data:DZbctlK5s6ZIuuUN0FflaOzoC2+ZqpVzNnntlpPuEwdRInTwn7HAfs1Uv/1p0ncRxrl24Xt+qzu4MZLS4cijpOap1w8zd/6vurbAhXYlphTgKQRRD9b4JPvb5YWsp4Gw2fcTsqQD1MA5P+ak9+/U/zCnVnJkXujXuyFMsKu5WnE=,iv:W/32E9FfYF48qMJx6wM3kvfByIIzNjwF8zmCqS+9R+k=,tag:v9fty9lrI2IolE6Y3zn8Ww==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
