---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  #- ./qlora/ks.yaml
  #- ./mmseqs2/ks.yaml
  - ./boltz/ks.yaml
  - ./chai/ks.yaml
  - ./openssh-server/ks.yaml
  - ./dev-server/ks.yaml
  #- ./protenix/ks.yaml
  #- ./ligandmpnn/ks.yaml
  #- ./rfdiffusion/ks.yaml
  #- ./jupyterhub/ks.yaml
