---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ghost
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ghost:
        type: deployment
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/ghost
              # renovate: datasource=docker depName=docker.io/library/ghost
              tag: 5.105.0
            env:
              NODE_ENV: "production"
              url: https://blog.${SECRET_EXTERNAL_DOMAIN}
              database__client: sqlite3
              database__connection__filename: "/var/lib/ghost/content/data/ghost.db"
              database__useNullAsDefault: true
              database__debug: false
              mail__transport: "SMTP"
              mail__options__tls__rejectUnauthorized: false
              mail__from: "Rare Compute <${SECRET_SMTP_FROM}>"
              privacy__useRpcPing: false
            envFrom:
              - secretRef:
                  name: ghost-secret
            resources:
              requests:
                memory: 512M
              limits:
                cpu: "4"
                memory: 1Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 2368

    ingress:
      app:
        className: traefik-external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host "blog.${SECRET_EXTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: ghost-tls
            hosts: [*host]

    persistence:
      content:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 12Gi
        retain: true
        globalMounts:
          - path: /var/lib/ghost/content
