---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app velero
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: vmware
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-openebs
        image: openebs/velero-plugin:3.6.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    # https://github.com/vmware-tanzu/velero/issues/1533
    credentials:
      existingSecret: velero-secret
    configuration:
      # https://velero.io/docs/v1.5/api-types/backupstoragelocation/
      backupStorageLocation:
        - name: default
          provider: aws
          objectStorage:
            bucket: arc1-velero-backups
          config:
            region:
            profile: "default"
      # https://velero.io/docs/v1.5/api-types/volumesnapshotlocation/
      volumeSnapshotLocation:
        - name: default
          provider: openebs.io/cstor-blockstore
          config:
            bucket: raspbernetes-openebs-backups
            prefix: cstor
            namespace: openebs
            provider: gcp
    # Backup schedules to create.
    #schedules:
    #  daily-backup:
    #    schedule: "0 6 * * *"
    #    template:
    #      ttl: "120h"
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: BackupStorageLocation
              name: default
            patch: |
              - op: add
                path: /metadata/annotations/meta.helm.sh~1release-name
                value: velero
              - op: add
                path: /metadata/annotations/meta.helm.sh~1release-namespace
                value: velero
