---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./metrics-server/ks.yaml

  # TODO: Fix issue where node-feature-discovery conflicts with nvidia-device-plugin
  #- ./node-feature-discovery/ks.yaml

  - ./nvidia-device-plugin/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
