---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 33.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    deployment:
      enabled: true
      replicas: 1
    service:
      annotations:
        io.cilium/lb-ipam-ips: ${LB_TRAEFIK}
    env:
      - name: TZ
        value: "${TIMEZONE}"
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=0"
    ports:
      traefik:
        expose:
          default: false
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          enabled: true
          options: default
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
        proxyProtocol:
          trustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
        http3:
          enabled: true
      metrics:
        expose:
          default: false
    metrics:
      serviceMonitor:
        enabled: true
        namespaceSelector:
          any: true
    pilot:
      enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        ingressClass: traefik
        allowExternalNameServices: true
        publishedService:
          enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1536Mi
