---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app protenix
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      protenix:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"
        containers:
          app:
            image:
              repository: ghcr.io/rarecompute/protenix
              tag: rolling
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              INPUT: "/app/examples/7pzb.pdb"
              OUT_DIR: "/app/output"
            securityContext:
              capabilities.drop: ["ALL"]
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: "16"
                memory: 16Gi
                nvidia.com/gpu: 4
    service:
      app:
        controller: *app
        annotations:
        ports:
          http:
            port: &port 80
    persistence:
      sharedmem:
        type: emptyDir
        medium: Memory
        sizeLimit: 64Gi
        globalMounts:
          - path: /dev/shm
      workspace:
        existingClaim: qlora-workspace
        globalMounts:
          - path: /workspace
