apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:T8qs49Z4y+kdjEQBRm1ZzUaI4A==,iv:GAoCxFa9UjJPuXmDgWGd52L5E/8zWaZwjVkX6OnSjvI=,tag:GpFHts+a6oNAA4lI0B2U9Q==,type:str]
  SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:Qc5JaSqkyNeO+8HUdJE=,iv:XI/XbWNWN1U4IE0YcnAupGAYQ1KJusL9+kMiMumGdv8=,tag:KidlnbPXT5oVx1IBZuDwZg==,type:str]
  SECRET_ALTERNATE_DOMAIN: ENC[AES256_GCM,data:QfEmE4r/icoTBxjkIKLzvc0nPMrwc/A=,iv:mUrL+FjaPAj36hsVi3Kyl5W8GoZr1hG7Z0kkH8ScVoM=,tag:2+Lk7MJGer+vc/1b/YZIjQ==,type:str]
  SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:zRk130CO6dmoZxIhyTdPZTDCKQ==,iv:l3HFnatyXtPilVcdflndrZGfhjqWAv5EshETwFM5BY0=,tag:UcBM26h7TiHoPD3606qpEQ==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:p9ilnWR3V/lMQQilei3/qgjtE9hoiFahaGPl0ZUkp2TA,iv:gIKkUsKcJtE6UbUxUgwGyUNh6lW5cD8+dG73Z5ew+3c=,tag:JPTvOAvwlHg+Z9uc7PTGRw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YStXYnp1VEZ1bElhV0gz
        bmFxdFpkczBtSXprUTVjenFNaTdOenZXTVI4CitkVDNiWHVDSDVManpKTGJjUDJJ
        R01KOEhvQVNZeFZ6SWhCNTBjNldaN0kKLS0tIE9SSDFwc08vRE1lSUU4dWxVdjlM
        L0NYaGZuTU9QdmFITjZEbGxJSkp5ZVkKmDZ7HwUH7YAHzqSIRN+ZTosBNUHYdCyA
        LZTIxEivw9qnHrzxme8BbSatbPRhJJ6wEiRm/olThuoTYUjq4OS3XQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-22T17:23:26Z"
  mac: ENC[AES256_GCM,data:FvfOJoFdkjhe61dzy+DqmxaoUnoqjKzFZtLvQ2zyUohejMNXxhgMxWgTYnSRNawV+uObI1zE1fPUDImFMDRUvhxrlczI04NNSOkzVs9ShNSgAZPXXyCikMqDV11pH3qB87ug/XhEW04Z7gtsNT6B3b8wheq20xBgUcdwXKfO8pE=,iv:5X+ZyEoIldJzuPq9CFgGe5vb/ogXh4WTGM10tDguqVs=,tag:I+KJJKJuBSxzAqbqA9flIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
