apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YULIX/4GDmJRR/6tZEJGYz7G/A==,iv:n3wL4hzYEDFNMmX5SBtwvrDciNdUVZjxqzhKY7VpG10=,tag:XNNBz0nUo5cBKMl62ZqBDA==,type:str]
  SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:hA2n9hqpGrssCWTIHuU=,iv:acFqr1UklRqiVWLkIR2k2YMPZhJhRhA3E9f/q3cqcBg=,tag:21rYMGHHknmVIvGvFUBOig==,type:str]
  SECRET_ALTERNATE_DOMAIN: ENC[AES256_GCM,data:uan7u456ycfUE+X5L1T6S3yqlHRRa/c=,iv:vqBfZXZnxIQenolLGckhgG0unidMw1IABLG6YnZ3El8=,tag:Xk/jROFVynku7vCS9gBWMw==,type:str]
  SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:pquDhHAhdP/Z+/DQTNE5CJD8Ww==,iv:httvlHQsY0bYzaVYlwvfuxPrFO9QVnSrARPddZQdyPE=,tag:hhyqn4/8W90yCWNghpg5Kw==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:+LG7n0E5y4aQ+FBXYijIiq505OqwAYsxt5Ng+NKZmcNV,iv:Yhe34lqeQ99R+vnewUA7xYh3jx/IBvapneSGkswFAhQ=,tag:udatdGnFnlAYSkcO9IZ0OQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UEZDajRGSEZ0NlFNK0s4
        TFgvMVpkN2pQUkVKMytoQk8vQW5jRk0xSEdzCjVkemNzamQ2Z1lxdmtoMGdCUEdD
        clZ2cTBOaFdYUDFUa1VvT29iN1JGRU0KLS0tIGdCYjhwNUdMdjREZDl0eEtWcExs
        NlZjMEFlVUd0L0MxTHo5OWk0TnFYSDAKqNHjlC7xS9k5YGxZ22G3ku6R12DxDcs0
        frcSHO9fR8A2MFY01M2RMTflzGjlOQiwHjHRGvFkZ/ZNRfdoCcRfzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-11T18:10:50Z"
  mac: ENC[AES256_GCM,data:uEau+NPCLwanUNVm3Vd2FzG40eE4tmcdRPjQDA2hQoJgeTACuQLLwS52L/3BpjBqOPnT2f+8iIlyGPj36z5DpgR9/VD63jUHcUkgDHvaRpfDJKqaPuwQKSmAlD5u+hwdIZsBVy454L78VXIiDgmeGt56M4Has5J6F+hxSkqTZEs=,iv:x44ywBGAQKOBiz7PcyLkZgz4PlaA3QJgNYGcyN7+IxU=,tag:2y6+Qgf8APwut8CLefddHA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
