---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  LETSENCRYPT_ENVIRONMENT: production
  CLUSTER_NAME: arc1

  CLUSTER_CIDR: "10.246.0.0/16"
  SERVICE_CIDR: "10.88.0.0/16"
  NODE_CIDR: "/24"
  VPN_CIDR: "10.201.0.0/24"
  MGMT_CIDR: "10.99.100.0/24"

  NFS_HOST: 10.28.20.10
  NFS_PATH: /mnt/r720xd-nvme/r720xd-nfs

  LB_TRAEFIK: 10.2.12.100
  LB_TRAEFIK_EXTERNAL: 10.2.12.101
  LB_POSTGRES: 10.2.12.102
