---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./descheduler/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  - ./volsync/ks.yaml
