apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2Bgq4VybdgL1a1rexDyfXbQcXaD+KnaDCStJjhtbhZOwrNFeC5pTgA==,iv:CiWHiQ+8DeamUDGGnfbd69xSsNlSkKWT5IRin0OPpLU=,tag:tmeTEew1J9WxwRlpcTphDQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ey3reuxyffqynll464r4q3tlhq5v73nxesyktr44lfez8jzxm94s0644n7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb2pVZUVzZjJabnR6b2o0
        REpOUktScUh3cUQ2NWZpdE1RVXJCQ1o1QlV3CmVSaSs1cEpFTUJvTDJSbERZUnBV
        QUJuWDdHaDhMMzBWbjQrejNwSWFIMFkKLS0tIDdYRDJHdFFJeFU4eEVBWUR4ZlFI
        ZFMzOTdEQTBPU00wc2NJTlBpVDVOREEKDH+lfCxeQjSgKHxjzvxeNxn50WkxlPrF
        Q3XWAbICHoRfD4HMt0BDRMaRZrkpVHi1ItYa9QYIQQRWb+YPGFALLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-14T01:18:57Z"
  mac: ENC[AES256_GCM,data:V4S8eO8XLv2qdhuZoXONMsxRXiHDBwOYOTUHcFbwNHI1k98N8OJB3+z9qJlzKP+YYvMYhHnKL2EkPo+c3Httz/lSXoI7vK0AaOKzlIJAi9KQyhE/iaRo/Ncd0JRTJonDCTrjshpfQb3rdkZXJnm+CkEgRRSP8yW3QFLOahunH0A=,iv:kOaBD+5Ekr5D0y1VwhbnTJ+2fdhDsZay7MjssGExQQ0=,tag:BFdO4IEupeTnUs59LYkddA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
