---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-1
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0-30
  primaryUpdateStrategy: unsupervised
  storage:
    size: 64Gi
    storageClass: local-nvme
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "512"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 250m
      memory: 4Gi
    limits:
      memory: 8Gi
  monitoring:
    enablePodMonitor: true
