---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    io.cilium/lb-ipam-ips: "${LB_POSTGRES}"
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-1
    role: primary
