---
# yamllint disable
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: Finish this, test MMSeqs2-App
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ollama:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/soedinglab/mmseqs2
              tag: master
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 200m
                memory: 4Gi
                # gpu.intel.com/i915: "1"
              limits:
                cpu: 8000m
                memory: 8Gi
                # gpu.intel.com/i915: "1"
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8877
    # maybe https://github.com/soedinglab/MMseqs2-App
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Research
          gethomepage.dev/name: MMSeqs2
          gethomepage.dev/description:
          gethomepage.dev/icon: *app
        hosts:
          - host: &host "mmseqs2.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: mmseqs2-tls
            hosts: [*host]
    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteMany
        size: 1024Gi
        retain: true
        globalMounts:
          - path: /models
