---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ollama:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.4.1
            env:
              TZ: ${TIMEZONE}
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_MODELS: /models
              #HSA_OVERRIDE_GFX_VERSION: "11.0.0"
            resources:
              requests:
                cpu: 200m
                memory: 4Gi
                # gpu.intel.com/i915: "1"
              limits:
                cpu: 8000m
                memory: 8Gi
                # gpu.intel.com/i915: "1"
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 11434
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Research
          gethomepage.dev/name: Ollama
          gethomepage.dev/description: LLM server
          gethomepage.dev/icon: *app
        hosts:
          - host: &host "ollama.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: ollama-tls
            hosts: [*host]
    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 64Gi
        #retain: true
        globalMounts:
          - path: /models
